### ISSUE TITLE
Documentation slow to build

### ISSUE THREAD

**Issue by albinahlback** [thofma/Hecke.jl#167]
Pretty irrelevant, but
```
@time include("make.jl")
...
251.851335 seconds (327.10 M allocations: 16.274 GiB, 2.72% gc time)
```
How can I speed things up?

**Comment by fieker** [comment]
using Revise, Hecke
and then run the documentation repeatedly in the same julia session helps. The second time round is (of course) much faster.

**Comment by albinahlback** [comment]
Hmm, but I think that only helps me after I've run it once.

**Comment by thofma** [comment]
Yes. The problem is that executes Hecke code to produce examples. There are some blocks of the form
``runthisexample
Qx, x = QQ["x"]
K, ...
``
which get evaluated and then the output is inserted in the documentation. One could remove this at the cost, that the examples could diverge from the actual output.

**Comment by fieker** [comment]
On Thu, Feb 18, 2021 at 03:43:28AM -0800, Albin Ahlbäck wrote:
> Hmm, but I think that only helps me after I've run it once.

Yep, the first time round it has to compile Hecke (and Doumenter and
such)
