### ISSUE TITLE
Equality of `ambient_space` for `ZLat`.

### ISSUE THREAD

**Issue by StevellM** [thofma/Hecke.jl#537]
```
julia> A = root_lattice(:A,3)
Quadratic lattice of rank 3 and degree 3 over the rationals

julia> B = root_lattice(:A,3)
Quadratic lattice of rank 3 and degree 3 over the rationals

julia> A == B
false

julia> VA = ambient_space(A)
Quadratic space over
Rational Field
with Gram matrix
[2 -1 0; -1 2 -1; 0 -1 2]

julia> VB = ambient_space(B)
Quadratic space over
Rational Field
with Gram matrix
[2 -1 0; -1 2 -1; 0 -1 2]

julia> VA == VB
false
```
Looking at the code, it seems that the equality of `ZLat` depends on whether or not those lattices have the same `ambient_space`. But equality of these ambient spaces an equality as julia object (`===`)... in this way, in the obvious case as above, we can't check whether or not a same lattice with a different name is equal to itself. I mentioned it in my recent commits: if I construct the root lattice `D3`, even stating it as being the same as `A3`, I can't directly check equality of them 
```
julia> root_lattice(:D,3) == root_lattice(:A,3)
false
```

**Comment by simonbrandhorst** [comment]
I agree.

**Comment by thofma** [comment]
I am not too fond of changing `==` of quadratic or hermitian spaces since this is how comparison works all other "parent objects". What quadratic and hermitian spaces are missing is caching by default. I think adding it would make the above work. By caching I mean the following behaviour: 

```julia
julia> Qx, x = PolynomialRing(QQ, "x")
(Univariate Polynomial Ring in x over Rational Field, x)

julia> QQx, x = PolynomialRing(QQ, "x")
(Univariate Polynomial Ring in x over Rational Field, x)

julia> Qx == QQx # in fact === holds
true

julia> QQx, x = PolynomialRing(QQ, "x", cached = false)
(Univariate Polynomial Ring in x over Rational Field, x)

julia> Qx == QQx
false
``` 

I propose to inroduce it the same mechanism to quadratic and hermitian spaces, so that then (by default)
```julia
julia> quadratic_space(QQ, QQ[1 2; 2 1]) == quadratic_space(QQ, QQ[1 2; 2 1]) # at the moment this is false
true
```

**Comment by thofma** [comment]
P.S.: I can add that quickly.

**Comment by simonbrandhorst** [comment]
I disagree. For instance in the group part of oscar. 
I suppose the reason is that a huge number of groups can be created and then caching is maybe expensive?
Similarly a huge number of lattices might be created in some algorithm and caching an ambient space should take `O(n^2)`.
```
julia>  m = matrix(ZZ,2,2,[0,1,1,0])
[0   1]
[1   0]

julia> matrix_group([m])
Matrix group of degree 2 over Integer Ring

julia> G = matrix_group([m])
Matrix group of degree 2 over Integer Ring

julia> H = matrix_group([m])
Matrix group of degree 2 over Integer Ring

julia> G===H
false

julia> G==H
true

julia> S1 = symmetric_group(4)
Sym( [ 1 .. 4 ] )

julia> S2 = symmetric_group(4)
Sym( [ 1 .. 4 ] )

julia> S1 == S2
true

julia> S1 === S2
false
```

**Comment by simonbrandhorst** [comment]
Note that quadratic_spaces as we implemented them do not have elements. But okay they are similar to parents.

**Comment by thofma** [comment]
I don't think the group part (in particular the matrix group stuff) of Oscar is that well tested or used:
```julia
julia> G = matrix_group([m, m])
Matrix group of degree 2 over Integer Ring

julia> H = matrix_group([m])
Matrix group of degree 2 over Integer Ring

julia> G == H
[Boom]
```
And I don't think this notion of equality will stay (for n > 2 I don't even if know whether this is known to be decidable.)

Also I don't consider quadratic spaces as things that have some common overstructure like symmetric groups or matrix groups.

1. I agree that caching adds some additional overhead when creating lattices/spaces and it is `O(n^2)`. We are talking here about times in the range `0.5µs` vs `1µs`.
2. On the other hand, it is much more economic in case one has many lattices with the same ambient space since it will then be created only once.
3. In my opinion having two "parent" objects floating around that are considered equal but not identical is always awkward. In particular if we save attributes/properties on the object. Then some of them will have the property set and some will have it not set, although at the same time the objects are equal.

**Comment by simonbrandhorst** [comment]
As for your example I think that matrix_group was designed with finite fields as base rings in mind. Perhaps the choices are more reasonable then. If I recall correctly, the reason to not have caching in group theory is that equality is too expensive (or maybe even undecidable in some infinite group cases).  So  that does not apply for quadratic spaces - 
1.O(n^2) is not too bad you're right.
2. O.k. for the casual user that is true. Anyone else (hopefully) just carries the parent around. Though sometimes even we do not and then our code actually relies on caching. That is super annoying when one turns caching off for some reason. (For instance in sage there is some memory leak because of caching. So for any serious computation I had to turn caching off.) If the memory leaks are somehow now problem in julia, then I have no real objection. 
3. Does not really apply to quadratic spaces (most properties are quite cheap to compute e.g. isisotropic)
To me both ways seem o.k. Your decision. You're the boss :-).

**Comment by fieker** [comment]
On Sun, Jan 16, 2022 at 06:05:42AM -0800, Tommy Hofmann wrote:
> I don't think the group part (in particular the matrix group stuff) of Oscar is that well tested or used:
> ```julia
> julia> G = matrix_group([m, m])
> Matrix group of degree 2 over Integer Ring
> 
> julia> H = matrix_group([m])
> Matrix group of degree 2 over Integer Ring
> 
> julia> G == H
> [Boom]
> ```
> And I don't think this notion of equality will stay (for n > 2 I don't even if know whether this is known to be decidable.)
> 
> Also I don't consider quadratic spaces as things that have some common overstructure like symmetric groups or matrix groups.
> 
> 1. I agree that caching adds some additional overhead when creating lattices/spaces and it is `O(n^2)`. We are talking here about times in the range `0.5µs` vs `1µs`.
yep - if this is THE critical part, there is always cached = false...
> 2. On the other hand, it is much more economic in case one has many lattices with the same ambient space since it will then be created only once.
yep
> 3. In my opinion having two "parent" objects floating around that are considered equal but not identical is always awkward. In particular if we save attributes/properties on the object. Then some of them will have the property set and some will have it not set, although at the same time the objects are equal.
agreed

**Comment by fingolfin** [comment]
> I don't think the group part (in particular the matrix group stuff) of Oscar is that well tested or used:
> 
> ```julia
> julia> G = matrix_group([m, m])
> Matrix group of degree 2 over Integer Ring
> 
> julia> H = matrix_group([m])
> Matrix group of degree 2 over Integer Ring
> 
> julia> G == H
> [Boom]
> ```

This is because nobody tested with integer matrices; the above works if you change the definition of `m` to use `QQ` instead of `ZZ`. I'll submit a fix. But in the end, you'll easily be able to find similar "boom"s by taking matrices over other Oscar rings for which we have no isomorphisms to GAP yet -- as there are a gazillion of them on the Oscar side, this is a game of catch up we can't win on the group theory side, we'll need (a) issue submissions for any such problem you run into, and then (b) deal with each ring individually -- for some there are GAP counterparts, for others there are workaround, and for some the theory simply does not exist and we'll have no choice to throw up our hands and give up.

Of course we could also change the matrix group constructors to reject any rings not in a certain list of supported rings, and give a more meaningful error for those, but I am not sure if that's helping more than it hurts?

> 
> And I don't think this notion of equality will stay (for n > 2 I don't even if know whether this is known to be decidable.)

It isn't in general, but I don't see why that means we need to introduce gotchas that'll lead to people writing code that will sometimes silently produce wrong results?

If the answer can't be decided, we can try some things ("obvious" containment, at least one of the groups is finite, etc.) and finally give up an produce an error, or run into an infinite loop (which the user can cancel via ctrl-c).

> 
> Also I don't consider quadratic spaces as things that have some common overstructure like symmetric groups or matrix groups.
> 
> 1. I agree that caching adds some additional overhead when creating lattices/spaces and it is `O(n^2)`. We are talking here about times in the range `0.5µs` vs `1µs`.

Caching concerns and overhead is also a reason why we currently don't even try to return "identical" parents in the group context.

Indeed, if `x` is a group element then in general `parent(x) == parent(x)` but `parent(x) !== parent(x)`. We could change the latter, but right now I am not sure it is worth it? And do the parent docs prescribe this behaviour? I couldn't find anything on that (but perhaps I just overlooked it, or perhaps it was forgotten to write it down).

Anyway, this is something we could certainly change in the groups part, it'll just come with some extra overhead (because we'll have to create these parents and carry them around, even in cases were they are not needed).


> 2. On the other hand, it is much more economic in case one has many lattices with the same ambient space since it will then be created only once.
> 3. In my opinion having two "parent" objects floating around that are considered equal but not identical is always awkward. In particular if we save attributes/properties on the object. Then some of them will have the property set and some will have it not set, although at the same time the objects are equal.

If we expect to need properties stored in parents, then this is indeed awkward. On the other hand, being forced to carry around (and even create(!)) parents all the time even in cases were you don't need them is also very awkward. You win some, you loose some...

**Comment by fingolfin** [comment]
CC @ThomasBreuer
